version: '3.8'

volumes:
  postgres-data:

services:
  app:
    env_file: devcontainer.env
    container_name: javadev
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    env_file: devcontainer.env
    container_name: postgresdb
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data